### ISSUE TITLE
Aliasing namespace

### ISSUE THREAD

**Issue by nam-co** [pkboom/laravel-tinker-on-vscode#1]
Hi pkboom thanks for the work on the package, are you planing to continue working on it? thanks

Also is it posible to add auto namespace aliasing? for example: aliasing 'User' to 'App\Models\User'

**Comment by pkboom** [comment]
The package uses laravel tinker behind the scene.
Use tinker.config.php. Refer to the link: https://tighten.co/blog/supercharge-your-laravel-tinker-workflow/

**Comment by pkboom** [comment]
Hey, it's a bit late. But auto namespace aliasing is done. The package works the same as tinker now.
